spring:
  datasource:
    url: jdbc:mysql://localhost:3306/koh_tanikawa_archives?serverTimezone=JST
    username: foo
    password: bar
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

server:
  servlet:
    context-path: /

app:
  image-path: https://xxxxxx.s3-ap-northeast-1.amazonaws.com/image/